### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ethus3h** [encukou/lastscrape-gui#11]
Using the Windows version 0.0.6, using Wine on OS X 10.11, got this error (last.fm username forestflight):
```
Please report the bug at:
 http://bugs.foocorp.net/projects/lastscrape-gui/issues/new

Traceback (most recent call last):
  File "gui.pyc", line 344, in run
  File "lastexport.pyc", line 168, in get_tracks
  File "lastexport.pyc", line 138, in parse_track
AttributeError: 'NoneType' object has no attribute 'get'
```
Also note that the bug report link is dead....

**Comment by FromQwghlm** [comment]
We can get this kind of error when scrobbling process is active, pay attention to this
