### ISSUE TITLE
libreimport.py: Timeouts around 6500 to 9000 lines or what? (Traceback)

### ISSUE THREAD

**Issue by Pendrokar** [encukou/lastscrape-gui#16]
Got 40000 of scrobbles to import. Had to use "awk" command to cut it up in order to avoid duplicates. Once it stopped at 6k, twice at 7k and once on 8k. Might be due to reloading the website.

OS: Ubuntu Bash on Windows 10

`Traceback (most recent call last):                                                                                        
File "./libreimport.py", line 51, in <module>                                                                             
scrobbler.add_track(ScrobbleTrack(timestamp, track, artist, album, trackmbid))                                        
File "/home/user/scrobble.py", line 83, in add_track                                                                      
self.submit(sleep_func)                                                                                               
File "/home/user/scrobble.py", line 62, in submit                                                                         
response = urlopen(self.submit_url, urlencode(data)).read()                                                           
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen                                                                
return opener.open(url, data, timeout)                                                                                
File "/usr/lib/python2.7/urllib2.py", line 429, in open                                                                   
response = self._open(req, data)                                                                                      
File "/usr/lib/python2.7/urllib2.py", line 447, in _open                                                                  
'_open', req)                                                                                                         
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain                                                            
result = func(*args)                                                                                                  
File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open                                                             
return self.do_open(httplib.HTTPConnection, req)                                                                      
File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open                                                               
r = h.getresponse(buffering=True)                                                                                     
File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse                                                           response.begin()                                                                                                      
File "/usr/lib/python2.7/httplib.py", line 453, in begin                                                                 
version, status, reason = self._read_status()                                                                         
File "/usr/lib/python2.7/httplib.py", line 417, in _read_status                                                           
raise BadStatusLine(line)                                                                                           
httplib.BadStatusLine: ''     
`

**Comment by regagain** [comment]
Just wanted to chime in & say that I have the same issue.

**Comment by Coul33t** [comment]
Could you please provide me with your LastFM username so that I can try to reproduce the bug locally?

**Comment by Pendrokar** [comment]
In my case it is the same username:
[](https://www.last.fm/user/pendrokar)

Though if you notice I haven't tried importing for almost a year.

**Comment by Coul33t** [comment]
Sorry for the delay, I was going through a tunnel. Fixed in 6d3bf45c0cd4acb6ab26061d08c44519c8ab7654
