### ISSUE TITLE
Time displayed incorrectly

### ISSUE THREAD

**Issue by desire7** [encukou/lastscrape-gui#9]
Hello, in version 0.0.6 instead of date and time of the scrobble, strange 10-digit numbers are displayed when saving the scrobbles to a text file. Used to be fine in 0.0.5, but 0.0.5 is not working anymore, displaying the following error:
Traceback (most recent call last):
  File "gui.pyc", line 345, in run
  File "lastscrape\lastscrape.pyc", line 86, in fetch_tracks
AttributeError: 'NoneType' object has no attribute 'findAll'

Is there a way to get the time displayed correctly not only while running the exe, but also in the text file?
Thanks.

**Comment by fiatjaf** [comment]
The strange 10 digits are Unix timestamp values. You can convert them to readable date formats using _datetime_ libraries from any programming language or by following [these instructions](http://stackoverflow.com/a/3249936/973380) in your terminal.

**Comment by desire7** [comment]
This is too difficult for an inexperienced user, but thank you.
